### ISSUE TITLE
[Idea]: merge sending code to the kernel here as well

### ISSUE THREAD

**Issue by WhiteBlackGoose** [lkhphuc/jupyter-kernel.nvim#6]
This plugin is amazing. But as something called "jupyter-kernel", it feels like it's missing a bit.

We can somehow merge [my fork of magma](https://github.com/WhiteBlackGoose/magma-nvim-goose) with your plugin. That will allow sending code to the kernel as well (by selecting code and sending it).

Both plugins provide object inspection, but differently. So I'd keep both calling them smh like "InspectBrief" and "InspectDetailed".

What do you think? (my fork requires some cleaning, so I'm not making PR right now & I need to know if you like this idea)

**Comment by lkhphuc** [comment]
Hi @WhiteBlackGoose , thank for your idea.

My current scope for this plugin is to be front-end agnostic, since as much as I like neovim, there is no universal "best interface" to interact with jupyter kernel. Some people only need sending to REPL, some might need to send and interact with the kernel manually. For some the notebook browser view are essential due to widgets etc. 

I am happy to see other plugin (like jupynium.nvim) to be inspired and include these features to their plugin as well. So if magma.nvim is working fine for you and you would like to incorporate these feature, please feel free to do so. 

With that said, I think just sending code to the kernel, without receiving and displaying any replies, could be done easily and still within the scope.
Is that what you have in mind?

I am just afraid that it would be redundant since you would still need to have a front end plugin to display the output of what you send anyway (vim-slime for me, magma for you and jupynium for other etc.)

**Comment by WhiteBlackGoose** [comment]
I use magma for output currently. Jupyter-kernel is nice, but it's a bit verbose for most of my use-case. I use jupyter-kernel for auto-completion personally.

What I suggested is adding sending code to kernel (doesn't matter if the user uses notebook or console or anything else) to this plugin, so that you wouldn't need two plugins for full interactive experience.

**Comment by lkhphuc** [comment]
If it just sending code to kernel, basically a command `JupyterExecute` that wrap aroud `self.client.execute(code)`, I could add that feature.

If you are free, do you mind elaborating on how would this improve your Magma's workflow? I though magma includes command to send to kernel already, so in order to get the result popup, you would need to send via magma anyway?

**Comment by WhiteBlackGoose** [comment]
It wouldn't improve my magma workflow, it would remove it, and I'd just use one plugin. That was my initial idea.

> If it just sending code to kernel, basically a command JupyterExecute that wrap aroud self.client.execute(code), I could add that feature.

Not sure if it'd be enough. It's quite a lot of work, so I'm just suggesting it to keep in mind, as a possibility

**Comment by lkhphuc** [comment]
Hi @WhiteBlackGoose , just to let you know if it helps your worflow. 

I just push the code for [`JupyterExecute`](https://github.com/lkhphuc/jupyter-kernel.nvim/commit/43b107ab79ca5f28c39d63c6f71784b613c33e33) , which wraps around `client.execute` function. It is very basic and not supporting display execution output, though I can send a line and inspect the assigned variable of the output, without having to leave the buffer.

I currently use this in addition to a jupyter (qt)console and quite happy with it. With this feature, I will close this issue, since I don't think I will ever implement execution output display or anything similar to magma.nvim here.

Hope this help and feel free to open another issue if you have any suggestion.
